### ISSUE TITLE
Błąd ładowania interfejsu IRequest przez autoload

### ISSUE THREAD

**Issue by adrian1207** [axotion/laravel-dotpay#1]
## Detailed description

Interfejs IRequest jest w katalogu evilnet/dotpay/src/DotpayApi/Contracts, natomiast jego namespace, jak i wszystkie odwołania z innych klas, są do Evilnet\Dotpay\Contracts (czyli bez podkatalogu DotpayApi)

## Context

Użycie klasy CreatePaymentLink powoduje błąd nie znalezienia implementowanego interfejsu IRequest.

## Possible implementation

Trzeba przenieść katalog Contracts piętro wyżej, do src, to rozwiązuje błąd.

## Your environment

Laravel 5.5.

**Comment by axotion** [comment]
Dzięki za wskazanie błędu. Jutro przeprowadzę testy i wypuszczę poprawioną wersję.

**Comment by axotion** [comment]
Problem rozwiązany
