### ISSUE TITLE
Dotenv\Exception\InvalidCallbackException

### ISSUE THREAD

**Issue by aanyszek** [axotion/laravel-dotpay#15]
Klasa DotpayManager metoda callback rzuca nieistniejący wyjątek: Dotenv\Exception\InvalidCallbackException.

# Środowisko
  "php": "^7.2.17",
 "evilnet/dotpay": "^2.1",
 "laravel/framework": "5.8.*",

**Comment by majweb** [comment]
Dalej nie działa...

**Comment by plumthedev** [comment]
zajmę się tym w najbliższym wolnym czasie, nie wygląda na nic bardziej poważnego
