### ISSUE TITLE
The POST method is not supported for this route

### ISSUE THREAD

**Issue by majweb** [axotion/laravel-dotpay#18]
Witam
Wszystko przebiega prawidłowo tylko jak wracam z ołatnośći do strony mam komunikat
The POST method is not supported for this route i przekierowuje mnie
http://127.0.0.1:8000/?status=OK
Gdzie robię błąd?

Top mój config
...
  'options' => [
        'url' => 'http://127.0.0.1:8000',
        'curl' => 'callback_url',
        'recipient' => [
            'company' => 'YourCompany',
            'address' => [
                'street' => 'ssssss',
                'building_number' => '11',
                'postcode' => '23232',
                'city' => "Warszawa"
            ]
        ],
    ]

i co znaczy I dodaj swoją metodę do obsługi callbacku jako wyjątek w pliku VerifyCsrfToken (Potrzebne by uderzenia POST z dotpaya nie wymagały tego tokenu)

**Comment by KamilGrzechulski** [comment]
@majweb 

Wejdź do pliku app\Http\Middleware\VerifyCsrfToken.php

class VerifyCsrfToken extends BaseVerifier
{
    protected $except = [
        // Place your URIs here
    ];
}

I dodaj do tablicy swoje adres route z którego przekierowuje dotpay.
