### ISSUE TITLE
CreatePaymentLink bez nazwy użytkownika i hasła

### ISSUE THREAD

**Issue by assghard** [axotion/laravel-dotpay#22]
Cześć.
Czy jest możliwe wykonanie płatności (CreatePaymentLink) bez podawania nazwy użytkownika i hasła w konfiguracji (dotpay.php i .env) ?

DOTPAY_USERNAME=
DOTPAY_PASSWORD=

Jak zostawię puste jest błąd: `401 Unauthorized` response: {"detail":"Authentication credentials were not provided."}

**Comment by plumthedev** [comment]
@assghard nie jest to możliwe :)   
Dotpay wymaga autoryzacji co z resztą widać po [zwróconym statusie HTTP](https://httpstatuses.com/401)
