### ISSUE TITLE
Dodanie autoloadera dla wersji 5.5 i wzwyż

### ISSUE THREAD

**Issue by axotion** [axotion/laravel-dotpay#3]
Laravel 5.5 wprowadził wsparcie autoładowania paczek bez ręcznego rejestrowania providera. Fajnie by było gdyby ktoś to mógł wprowadzić i przetestować czy dobrze działa.

**Comment by adrian1207** [comment]
Wprowadzone i przetestowane, szczegóły w pull request #4
