### ISSUE TITLE
[Question] Kiedy i jak wyłapać callback?

### ISSUE THREAD

**Issue by adrian1207** [axotion/laravel-dotpay#5]
Cześć, dzięki za paczkę, bardzo przydatna. :)

Mam szybkie pytania o callback, jeśli możesz podpowiedzieć.

1. Czy dotpay w trybie testowym wykonuje callbacki?
2. Jaki routing pod to przygotować? Post, czy get?
3. W którym momencie płatności wykonywany jest taki callback? Czy mogę w etapie końcowym płatności poczekać aż dotpay wykona curla?

**Comment by axotion** [comment]
1. Tak, wykonuje. Musisz zarejestrować swoje testowe konto 
https://ssl.dotpay.pl/test_seller/test/registration/

2. Pod wysyłkę POST, callback odpowie postem na CURL, a przekieruje użytkownika po URL

3. Gdy użytkownik zapłaci/nie zapłaci wtedy zostaje wykonany callback na CURL
