### ISSUE TITLE
Brak parametru CHK - wymagany od września tego roku

### ISSUE THREAD

**Issue by adrian1207** [axotion/laravel-dotpay#9]
Na nowych kontach Dotpay ta integracja nie zadziała. W marcu tego roku Dotpay wprowadził parametr CHK jako ochronę integralności parametrów przekierowania, od września na nowych kontach jest ona wymagana i trzeba pisać do Dotpay o ewentualne wyłączenie.

Tutaj szczegóły: https://ssl.dotpay.pl/s2/login/cloudfs1/magellan_media/common_file/dotpay_instrukcja_techniczna_implementacji_platnosci.pdf

**Comment by axotion** [comment]
https://github.com/axotion/laravel-dotpay/pull/8
